#!/usr/bin/env python3
"""Export cookies from the connected Chrome (via CDP) to Netscape format for yt-dlp."""
from playwright.sync_api import sync_playwright
from pathlib import Path
import time

OUT = Path("/Users/jax/bestdancer/assets/incoming/2026-W29/cookies.txt")

with sync_playwright() as p:
    browser = p.chromium.connect_over_cdp("http://127.0.0.1:9222")
    ctx = browser.contexts[0]
    cookies = ctx.cookies()
    lines = ["# Netscape HTTP Cookie File", "# generated by dump_cookies.py", ""]
    for c in cookies:
        domain = c.get("domain", "")
        if not domain:
            continue
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = int(c.get("expires", 0)) if c.get("expires", -1) not in (-1, None) else 0
        if expires <= 0:
            expires = int(time.time()) + 3600 * 24 * 30
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append("\t".join([domain, include_sub, path, secure, str(expires), name, value]))
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(cookies)} cookies to {OUT}")
